# docker-compose.yml

services:
  # The Application Service (PHP/Laravel)
  app:
    build: .
    container_name: ${APP_NAME}_app
    volumes:
      - .:/app
    networks:
      - app-network

  # The Web Server Service (Nginx)
  nginx:
    image: nginx:1.21-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  # The Database Service (MySQL)
  db:
    image: mysql:8.0
    container_name: ${APP_NAME}_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local